name: Update pipeline-status

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        docker build -t localbuild -f Dockerfile .
        docker run --rm -v $(pwd):/buildout localbuild
        mv buildout/README.md .
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Update README.md with latest pipeline-status
        branch: main
        file_pattern: README.md
        repository: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
